**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [2]:
import numpy as np

In [3]:
n=10

In [4]:
x = np.arange(n-1,0,-1)

In [5]:
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [6]:
n=7

In [7]:
#не совсем понятно, включает ли диапазон значения N и 0. Сделал по аналогии с заданием 1 (N не входит в диапазон, 0 входит)
a=np.diag(np.arange(n-1,-1,-1), k=0)
a

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [9]:
#считаем сумму элементов на диагонали
sum([x for x in a.diagonal()])

21

**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [10]:
import pandas as pd

In [11]:
#вытаскиваем две таблицы: Фильмы и Рейтинги
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [12]:
#соединяем их по столбцу movieId
joined = movies.merge(ratings, on='movieId', how='left')

In [13]:
#оставляем строки, где рейтинг = 5
joined_5=joined.query('rating==5.0')

In [147]:
#находим movieId фильма с максимальным кол-вом оценок 
#метод value_counts выдает список из двух столбцов в порядке убывания, по этому просто вытаскиваем индекс в строке 0
i_target=joined_5['movieId'].value_counts().index[0]

In [148]:
#для movieId с максимальным кол-вом оценок 5 выводим название фильма (title)
max_rating_index=joined_5.query('movieId=='+str(i_target)).head(1).index[0]
joined_5.query('movieId=='+str(i_target)).head(1).at[max_rating_index, 'title']


'Shawshank Redemption, The (1994)'

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.


In [79]:
import requests

In [80]:
#Открываем 'power.csv'
data = pd.read_csv('power.csv')

In [81]:
#ищем названия стран Латвия, Литва и Эстония на английском языке (как они заведены в базе)
data[ data['country'].str.contains('lit', case=False) ]['country'].unique()

array(['Lithuania'], dtype=object)

In [82]:
data[ data['country'].str.contains('lat', case=False) ]['country'].unique()

array(['Latvia'], dtype=object)

In [83]:
data[ data['country'].str.contains('est', case=False) ]['country'].unique()

array(['Estonia', 'State of Palestine', 'Timor-Leste'], dtype=object)

In [137]:
# формируем запрос по параметрам, данным в задании, и сохраняем отфильтрованную таблицу в новую переменную
data_filtered=data[ (data['year'] <= 2010) & (data['year'] >= 2005) & (data['quantity'] > 0) & ((data['country'] == 'Estonia') | (data['country'] == 'Latvia') | (data['country'] == 'Lithuania')) & ((data['category'] == 4) | (data['category'] == 12)  | (data['category'] == 21) ) ]

In [140]:
#Суммируем значения в столбце quantity
sum(data_filtered.quantity)

240580.0

**Задание 5**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [116]:
#    4x + 2y +  z = 4
#     x + 3y      = 12
#         5y + 4z = -3

In [117]:
from numpy import linalg

In [120]:
A = np.array([[4,2,1],[1,3,0],[0,5,4] ] )
B = np.array([4,12,-3])
linalg.solve(A, B)

array([ 0.46666667,  3.84444444, -5.55555556])

In [121]:
#проверка
np.allclose( np.dot(A, linalg.solve(A, B)), B )

True